## Numpy Array operations

In [2]:
import numpy as np 

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing ", arr[2:7])
print("With Step ", arr[1:8:2])
print("Negative indexing ",arr[-3])

Basic Slicing  [3 4 5 6 7]
With Step  [2 4 6 8]
Negative indexing  8


### 2D array slicing

In [20]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element :" , arr_2d[1,2])
print("Entire row :", arr_2d[1])
print("Entire column :", arr_2d[:,1])

Specific element : 6
Entire row : [4 5 6]
Entire column : [2 5 8]


### Sorting

In [24]:
unsorted = np.array([3,4,1,2,5,8,1,9,3,4,3,2])
print("Sorted Array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D array by row :", np.sort(arr_2d_unsorted, axis=0))
print("Sorting 2d array by column :", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 1 2 2 3 3 3 4 4 5 8 9]
Sorted 2D array by row : [[1 1]
 [2 2]
 [3 3]]
Sorting 2d array by column : [[1 3]
 [1 2]
 [2 3]]


### Filtaring 

In [26]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers :", even_numbers)

Even numbers : [ 2  4  6  8 10]


### Filter with mask

In [27]:
mask = numbers > 5 
print("Numbers greater than 5 :", numbers[mask])

Numbers greater than 5 : [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [30]:
indexing = [0,2,4]
print(numbers[indexing])

where_result = np.where(numbers > 5)
print("NP where :", numbers[where_result])

[1 3 5]
NP where : [ 6  7  8  9 10]


In [33]:
condition_array = np.where(numbers > 5, numbers * 2 , numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [36]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

combined = arr_1 + arr_2 # eta valu gula ke jog kore dibe 2 ta ke jora dibe na 
print(combined)
combined_2 = np.concatenate((arr_1,arr_2))
print(combined_2)

[5 7 9]
[1 2 3 4 5 6]


### Array compatibilty

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes :", a.shape == b.shape)

Compatibility shapes : True


In [8]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))

print(original)
print("***")
print(with_new_row)

print("***")

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))

print(original)
print("With new column :\n",with_new_col)


[[1 2]
 [3 4]]
***
[[1 2]
 [3 4]
 [5 6]]
***
[[1 2]
 [3 4]]
With new column :
 [[1 2 7]
 [3 4 8]]


In [10]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion :", deleted)

Array after deletion : [1 2 4 5]
