In [16]:
import numpy as np
import time

In [17]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [18]:
py_list = [1,2,3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [19]:
start = time.time()
py_list = [i*2 for i in range(1000)]
print("\n List operation time: ",time.time() - start)


start = time.time()
np_array = np.arange(1000) * 2
print("\n Array operation time: ",time.time() - start)


 List operation time:  0.00016236305236816406

 Array operation time:  0.0001494884490966797


### creating array from scratch

In [20]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.84053116 0.41746087 0.31210874]
 [0.12289127 0.70353393 0.80853149]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [21]:
vector = np.array([1,2,3])
print("Vector : ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor :",tensor)

Vector :  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Arrat properties

In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("Data type ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Data type  int64


### Array Reshaping

In [23]:
arr = np.arange(12)
print("Original array ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array ",reshaped)

flattened = reshaped.flatten()
print("Flattened array ",flattened)

# ravel ( original e change ane )
raveled = reshaped.ravel()
print("Raveled array ",raveled)

transpose = reshaped.T
print("Transposed array ",transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [24]:

# একটি ৩x৩ ম্যাট্রিক্স বা টেবিল তৈরি করলাম
# ইন্ডেক্স মনে রাখার ট্রিক:
# সারি (Rows)    ->   0 নম্বর: [10, 20, 30] | 1 নম্বর: [40, 50, 60] | 2 নম্বর: [70, 80, 90]
# কলাম (Columns) ->   0 নম্বর: [10,40,70]   | 1 নম্বর: [20,50,80]   | 2 নম্বর: [30,60,90]

arr = np.array([
    [10, 20, 30],  # সারি ০
    [40, 50, 60],  # সারি ১
    [70, 80, 90]   # সারি ২
])

print("--- ১. নির্দিষ্ট একটি উপাদান (Single Indexing) ---")
# নিয়ম: arr[row, column]
# এখানে row = 1 (মানে ২য় সারি), column = 2 (মানে ৩য় কলাম)
element = arr[1, 2] 
print("নির্দিষ্ট উপাদান:", element) # আউটপুট আসবে: 60
print("\n")


print("--- ২. ডাটা কেটে আনা (Slicing) ---")
# আমাদের টার্গেট কোড: arr[0:2, 1:3]
# স্লাইসিং এর গোল্ডেন রুল: [start : end] মানে হলো start থেকে (end - 1) পর্যন্ত।

# ১ অংশ [0:2] -> এটি সারির (Row) জন্য।
# হিসেব: শুরু হবে ০ থেকে, শেষ হবে (২ - ১) = ১ এ।
# অর্থাৎ, সে শুধু 'সারি ০' এবং 'সারি ১' কে কেটে নেবে। (সারি ২ বাদ!)

# ২য় অংশ [1:3] -> এটি কলামের (Column) জন্য।
# হিসেব: শুরু হবে ১ থেকে, শেষ হবে (৩ - ১) = ২ এ।
# অর্থাৎ, সে শুধু 'কলাম ১' এবং 'কলাম ২' কে কেটে নেবে। (কলাম ০ বাদ!)

sliced_data = arr[0:2, 1:3]

print("কেটে আনা নতুন ম্যাট্রিক্স:")
print(sliced_data)
# আউটপুট আসবে:
# [[20 30]     <- সারি ০ এর কলাম ১ ও কলাম ২
#  [50 60]]    <- সারি ১ এর কলাম ১ ও কলাম ২

--- ১. নির্দিষ্ট একটি উপাদান (Single Indexing) ---
নির্দিষ্ট উপাদান: 60


--- ২. ডাটা কেটে আনা (Slicing) ---
কেটে আনা নতুন ম্যাট্রিক্স:
[[20 30]
 [50 60]]


In [25]:
# মনে করুন এটি একটি ই-কমার্স অ্যাপের কিছু প্রোডাক্টের দাম (Prices)
prices = np.array([50, 120, 80, 200, 45, 300])

print("--- ১. ফিল্টারিং করার ম্যাজিক ---")

# আমাদের শর্ত: আমরা শুধু ১০০ টাকার বেশি দামি প্রোডাক্টগুলো দেখতে চাই
# ব্যাকঅ্যান্ডে NumPy প্রতিটা উপাদানের জন্য True অথবা False এর একটা 'মাস্ক' বানায়
expensive_mask = prices > 100 
print("শর্তের মাস্কটি দেখতে এমন হয়:\n", expensive_mask)
# আউটপুট: [False  True False  True False  True]
# (কারণ ১২০, ২০০, এবং ৩০০ হলো ১০০-এর চেয়ে বড়, তাই ওগুলো True)

# এবার এই মাস্কটি অরিজিনাল অ্যারের ভেতর পাস করলেই, সে শুধু True ডাটাগুলো কেটে আনবে!
expensive_prices = prices[prices > 100]

print("\n১০০ টাকার বেশি দামি প্রোডাক্টের লিস্ট:")
print(expensive_prices) 
# আউটপুট আসবে: [120 200 300]

--- ১. ফিল্টারিং করার ম্যাজিক ---
শর্তের মাস্কটি দেখতে এমন হয়:
 [False  True False  True False  True]

১০০ টাকার বেশি দামি প্রোডাক্টের লিস্ট:
[120 200 300]


In [33]:
# একটি সিম্পল ২-ডাইমেনশনাল ম্যাট্রিক্স নিলাম
matrix_data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("--- ২. ডাটার হিসাব-নিকাশ ---")

# ১. পুরো ম্যাট্রিক্সের সবগুলো সংখ্যার যোগফল (Sum)
total_sum = np.sum(matrix_data)
print("সব সংখ্যার মোট যোগফল:", total_sum) # ১+২+৩+৪+৫+৬ = ২১

# ২. পুরো ম্যাট্রিক্সের গড় মান (Mean/Average)
average = np.mean(matrix_data)
print("ডাটার গড় মান (Average):", average) # ২১ কে ৬ দিয়ে ভাগ করলে ৩.৫ হয়

# ৩. পুরো ম্যাট্রিক্সের মধ্যে সবচেয়ে বড় সংখ্যা (Maximum)
max_value = np.max(matrix_data)
print("সবচেয়ে বড় সংখ্যা কোনটি?:", max_value) # আউটপুট আসবে: ৬

# ৪. পুরো ম্যাট্রিক্সের মধ্যে সবচেয়ে ছোট সংখ্যা (Minimum)
min_value = np.min(matrix_data)
print("সবচেয়ে ছোট সংখ্যা কোনটি?:", min_value) # আউটপুট আসবে: ১

--- ২. ডাটার হিসাব-নিকাশ ---
সব সংখ্যার মোট যোগফল: 21
ডাটার গড় মান (Average): 3.5
সবচেয়ে বড় সংখ্যা কোনটি?: 6
সবচেয়ে ছোট সংখ্যা কোনটি?: 1
