# Data structure: [ restaurant_id, 2021, 2022, 2023, 2024]

In [4]:
import numpy as np

In [5]:
sales_data = np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,210000,240000,270000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])

print("--- Zomato sales analysis ---")
print("\n Sales data shape :", sales_data.shape)
print("First 3 restrorent data :\n", sales_data[:3])

--- Zomato sales analysis ---

 Sales data shape : (5, 5)
First 3 restrorent data :
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 210000 240000 270000]]


# Total sales per year

In [6]:
yearly_total = np.sum(sales_data[:,1:],axis=0)
print(yearly_total)

min_sales = np.min(sales_data[:,1:], axis=1)
print("Min sales",min_sales)

[ 810000  925000 1065000 1210000]
Min sales [150000 120000 200000 180000 160000]


In [7]:
max_sales_per_year = np.max(sales_data[:,1:], axis=0)
print("Max sales per year :",max_sales_per_year)

Max sales per year : [200000 210000 240000 270000]


In [8]:
vector_1 = np.array([1,2,3,4,5])
vector_2 = np.array([6,7,8,9,10])

print("Vector addition :", vector_1 +  vector_2)
print("\n Multiplication vector :", vector_1 * vector_2)
print("\n Dot product :", np.dot(vector_1,vector_2))

Vector addition : [ 7  9 11 13 15]

 Multiplication vector : [ 6 14 24 36 50]

 Dot product : 130


In [9]:
restaurant_type = np.array(["biryani","chinese","pizza","burger","cafe"])
vectorized_upper = np.vectorize(str.upper)
print("Vectorized Upper :", vectorized_upper(restaurant_type))

Vectorized Upper : ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(2,3))
print(y)